add radio
js-tasks-ru/htmlcss-20210513_bygermina pull request #16
Opened 2021-06-27 15:39 UTC by bygermina

2021-06-27 15:40 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-28 07:32 UTC, GSemikozov requested changes

2021-06-28 07:32 UTC, GSemikozov commented on 07-lection5/02-radio/radio.css
> +    width: 27px;
в макете это все-таки 28)

2021-06-28 07:32 UTC, GSemikozov commented on 07-lection5/02-radio/radio.css
> +    box-shadow: inset 0 0 0 3px white;
white надо бы заменить на белый из переменных)

2021-06-28 17:24 UTC, bygermina commented on 07-lection5/02-radio/radio.css
> +    width: 27px;
Исправила. Чего-то подумала, что 1px прибавится от бордера. Но 28 - это габарит, да?

2021-06-28 17:24 UTC, bygermina commented on 07-lection5/02-radio/radio.css
> +    box-shadow: inset 0 0 0 3px white;
исправила

2021-06-28 17:25 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-28 21:16 UTC, GSemikozov commented on 07-lection5/02-radio/radio.css
> +    width: 27px;
тогда прибавилось бы 2 - по 1 сверху и снизу

2021-06-28 21:16 UTC, GSemikozov commented on 07-lection5/02-radio/radio.css
> +    width: 27px;
надо проверить размер в девтулзах, если будет 30px - тогда зададим box-sizing: border-box

2021-06-29 17:43 UTC, bygermina commented on 07-lection5/02-radio/radio.css
> +    width: 27px;
Там задан border-box . Габарит 28

2021-06-29 19:50 UTC, GSemikozov approved these changes

2021-06-29 19:50 UTC, merged