Lesson3 task1 calendar
js-tasks-ru/htmlcss-20210513_bygermina pull request #6
Opened 2021-06-02 06:58 UTC by bygermina

2021-06-02 06:58 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-02 18:51 UTC, GSemikozov requested changes

2021-06-02 18:51 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +  float: left;
флоаты низзя использовать =) давай заменим выравнивание через флоаты выравнииванием через флекс-контейнер

2021-06-02 18:51 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +  width: 515px;
здесь и ниже - все фиксированные значение ширины заменим на проценты

2021-06-02 18:51 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +  grid-template-columns: repeat(7, 36px);
здесь в repeat можно не использовать четко фиксированное в пикселях значение - наоборот, гораздо правильнее будет использовать единицы измерения fr (как это было показано на лекции). Так мы сможем сделать действительно адаптивный календарь, который при сужении или расширении будет пропорционально уменьшаться / увеличиваться. То есть можно вот так: `repeat(7, 1fr)`

2021-06-02 18:51 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +  grid-template-rows: 48px repeat(5, 36px);
и тогда, в принципе, нет надобности размечать rows - можно удалить эту строку

2021-06-02 18:51 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +  font-size: 14px;
у _day по-моему 14px, а вот у item-а - 16px =)

2021-06-03 18:46 UTC, bygermina commented on 04-lection2/02-skeleton/skeleton.css
> +  float: left;
сделала

2021-06-03 18:46 UTC, bygermina commented on 04-lection2/02-skeleton/skeleton.css
> +  width: 515px;
сделала

2021-06-03 19:17 UTC, bygermina commented on 05-lection3/03-calendar/calendar.css
> +  font-size: 14px;
у обоих 16, я проверила и исправила

2021-06-03 19:21 UTC, bygermina commented on 05-lection3/03-calendar/calendar.css
> +  grid-template-columns: repeat(7, 36px);
Я исправила на fr. Но тогда получается что ячейка не 36 на 36px, а немного больше получается. У меня  36,28px на 36,11px . Это ничего страшного, или с этим надо боротьcя? И еще вопрос. Я попробовала уменьшать окно, календарь не масштабируется. Что у меня не  правильно?

2021-06-03 19:22 UTC, bygermina commented on 05-lection3/03-calendar/calendar.css
> +  grid-template-rows: 48px repeat(5, 36px);
если удалить rows , то все ячейки становятся одинаковой высоты. А там первый ряд 48px а остальные 36px в макете. Как это пофиксить, если удалить rows?

2021-06-08 13:51 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +  grid-template-columns: repeat(7, 36px);
это нормально, при том что ширина родителя может быть разной - а если мы жестко зафиксируем размеры, то наш компонент перестанет быть адаптивным, наоборот - клетки календаря будут вылазить за пределы обертки)

2021-06-08 13:52 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +  grid-template-rows: 48px repeat(5, 36px);
а для элементов первого ряда можно задать модификатор который проставляет нужные стили для шрифта (line-height будет выше, а значит и клетка тоже)

2021-06-08 13:53 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +  font-size: 14px;
<img width="945" alt="Screenshot 2021-06-08 at 16 52 50" src="https://user-images.githubusercontent.com/6191270/121197439-f9a6fa80-c879-11eb-8e44-063126b30e04.png">
вот это я имел в виду

2021-06-10 06:01 UTC, bygermina commented on 05-lection3/03-calendar/calendar.css
> +  font-size: 14px;
это исправила

2021-06-10 06:01 UTC, bygermina commented on 05-lection3/03-calendar/calendar.css
> +  grid-template-rows: 48px repeat(5, 36px);
это сделала

2021-06-10 06:01 UTC, bygermina commented on 05-lection3/03-calendar/calendar.css
> +  grid-template-columns: repeat(7, 36px);
это сделала

2021-06-10 09:58 UTC, GSemikozov approved these changes

2021-06-10 09:58 UTC, merged