Component page
js-tasks-ru/htmlcss-20210513_bygermina pull request #7
Opened 2021-06-02 10:05 UTC by bygermina

2021-06-02 10:06 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-02 18:53 UTC, GSemikozov requested changes

2021-06-02 18:53 UTC, GSemikozov commented on pages/template.css
> +.menu {
.menu и .component, поскольку это не элементы .page, а отдельные блоки - надо вынести отсюда в компоненты

2021-06-03 19:43 UTC, bygermina commented on pages/template.css
> +.menu {
сделала

2021-06-11 07:11 UTC, GSemikozov approved these changes

2021-06-11 07:11 UTC, merged